version: "3.8"

services:
  db:
    image: postgres:12
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: webscraper
      POSTGRES_PASSWORD: webscraper
    ports:
      - "5432:5432"