--liquibase formatted sql

--changeset joseribeiro:20200801-1
create table stock (id integer generated by default as identity not null, ticker varchar(6) not null, constraint stock_pkey primary key (id));

--changeset joseribeiro:20200801-2
alter table stock add constraint stock_ticker_key unique (ticker);

--changeset joseribeiro:20200801-3
alter table stock add column market_cap bigint;
alter table stock add column price_to_earnings decimal(2, 2);
alter table stock add column ev_to_ebitda decimal(2, 2);
alter table stock add column current_ratio decimal(2, 2);
alter table stock add column gross_debt_to_net_worth decimal(2, 2);
alter table stock add column return_on_equity decimal(2, 2);
alter table stock add column dividend_yield decimal(2, 2);
alter table stock add column dividend_payout decimal(2, 2);
